// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestCaseTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testCase() {
    // Test name: testCase
    // Step # | name | target | value
    // 1 | open | http://localhost:8000/ | 
    driver.get("http://localhost:8000/");
    // 2 | setWindowSize | 1440x790 | 
    driver.manage().window().setSize(new Dimension(1440, 790));
    // 3 | click | name=username | 
    driver.findElement(By.name("username")).click();
    // 4 | type | name=username | testsc@gmail.com
    driver.findElement(By.name("username")).sendKeys("testsc@gmail.com");
    // 5 | click | name=password | 
    driver.findElement(By.name("password")).click();
    // 6 | type | name=password | pqrst_cse2020
    driver.findElement(By.name("password")).sendKeys("pqrst_cse2020");
    // 7 | click | css=.infoForm | 
    driver.findElement(By.cssSelector(".infoForm")).click();
    // 8 | type | name=username | testsiop@gmail.com
    driver.findElement(By.name("username")).sendKeys("testsiop@gmail.com");
    // 9 | click | css=.button | 
    driver.findElement(By.cssSelector(".button")).click();
    // 10 | click | css=.Search > input | 
    driver.findElement(By.cssSelector(".Search > input")).click();
    // 11 | type | css=.Search > input | #trending
    driver.findElement(By.cssSelector(".Search > input")).sendKeys("#trending");
    // 12 | click | css=.followStatus > div | 
    driver.findElement(By.cssSelector(".followStatus > div")).click();
    // 13 | click | css=.PostShare > div > input | 
    driver.findElement(By.cssSelector(".PostShare > div > input")).click();
    // 14 | type | css=.Search > input | #trending
    driver.findElement(By.cssSelector(".Search > input")).sendKeys("#trending");
    // 15 | sendKeys | css=.PostShare > div > input | ${KEY_ENTER}
    driver.findElement(By.cssSelector(".PostShare > div > input")).sendKeys(Keys.ENTER);
  }
}
